
//! Autogenerated weights for pallet_poe
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-05, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `LAPTOP-KUMKVGJ6`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_poe
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/poe/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_poe.
pub trait WeightInfo {
	fn create_claim(d: u32, ) -> Weight;
	fn revoke_claim(d: u32, ) -> Weight;
	fn transfer_claim(d: u32, ) -> Weight;
}

/// Weights for pallet_poe using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn create_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1003521`
		// Minimum execution time: 17_063_000 picoseconds.
		Weight::from_parts(17_693_000, 1003521)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(4_087, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `90 + d * (1 ±0)`
		//  Estimated: `1003521`
		// Minimum execution time: 17_905_000 picoseconds.
		Weight::from_parts(17_984_000, 1003521)
			// Standard Error: 19
			.saturating_add(Weight::from_parts(12_391, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn transfer_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `90 + d * (1 ±0)`
		//  Estimated: `1003521`
		// Minimum execution time: 19_227_000 picoseconds.
		Weight::from_parts(19_467_000, 1003521)
			// Standard Error: 20
			.saturating_add(Weight::from_parts(12_470, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn create_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1003521`
		// Minimum execution time: 17_063_000 picoseconds.
		Weight::from_parts(17_693_000, 1003521)
			// Standard Error: 8
			.saturating_add(Weight::from_parts(4_087, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `90 + d * (1 ±0)`
		//  Estimated: `1003521`
		// Minimum execution time: 17_905_000 picoseconds.
		Weight::from_parts(17_984_000, 1003521)
			// Standard Error: 19
			.saturating_add(Weight::from_parts(12_391, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(1000056), added: 1002531, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 1000000]`.
	fn transfer_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `90 + d * (1 ±0)`
		//  Estimated: `1003521`
		// Minimum execution time: 19_227_000 picoseconds.
		Weight::from_parts(19_467_000, 1003521)
			// Standard Error: 20
			.saturating_add(Weight::from_parts(12_470, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}